/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsFastenersRouteImport } from './routes/products/fasteners'
import { Route as ProductsFlangesRouteImport } from './routes/products/flanges'
import { Route as ProductsGasketsRouteImport } from './routes/products/gaskets'
import { Route as ProductsPipeFittingsRouteImport } from './routes/products/pipe-fittings'
import { Route as ProductsPipesTubesRouteImport } from './routes/products/pipes-tubes'
import { Route as ProductsStructuralSteelRouteImport } from './routes/products/structural-steel'
import { Route as ProductsValvesRouteImport } from './routes/products/valves'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFastenersRoute = ProductsFastenersRouteImport.update({
  id: '/products/fasteners',
  path: '/products/fasteners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFlangesRoute = ProductsFlangesRouteImport.update({
  id: '/products/flanges',
  path: '/products/flanges',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGasketsRoute = ProductsGasketsRouteImport.update({
  id: '/products/gaskets',
  path: '/products/gaskets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPipeFittingsRoute = ProductsPipeFittingsRouteImport.update({
  id: '/products/pipe-fittings',
  path: '/products/pipe-fittings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPipesTubesRoute = ProductsPipesTubesRouteImport.update({
  id: '/products/pipes-tubes',
  path: '/products/pipes-tubes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsStructuralSteelRoute = ProductsStructuralSteelRouteImport.update({
  id: '/products/structural-steel',
  path: '/products/structural-steel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsValvesRoute = ProductsValvesRouteImport.update({
  id: '/products/valves',
  path: '/products/valves',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/quality': typeof QualityRoute
  '/products/fasteners': typeof ProductsFastenersRoute
  '/products/flanges': typeof ProductsFlangesRoute
  '/products/gaskets': typeof ProductsGasketsRoute
  '/products/pipe-fittings': typeof ProductsPipeFittingsRoute
  '/products/pipes-tubes': typeof ProductsPipesTubesRoute
  '/products/structural-steel': typeof ProductsStructuralSteelRoute
  '/products/valves': typeof ProductsValvesRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/quality': typeof QualityRoute
  '/products/fasteners': typeof ProductsFastenersRoute
  '/products/flanges': typeof ProductsFlangesRoute
  '/products/gaskets': typeof ProductsGasketsRoute
  '/products/pipe-fittings': typeof ProductsPipeFittingsRoute
  '/products/pipes-tubes': typeof ProductsPipesTubesRoute
  '/products/structural-steel': typeof ProductsStructuralSteelRoute
  '/products/valves': typeof ProductsValvesRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/quality': typeof QualityRoute
  '/products/fasteners': typeof ProductsFastenersRoute
  '/products/flanges': typeof ProductsFlangesRoute
  '/products/gaskets': typeof ProductsGasketsRoute
  '/products/pipe-fittings': typeof ProductsPipeFittingsRoute
  '/products/pipes-tubes': typeof ProductsPipesTubesRoute
  '/products/structural-steel': typeof ProductsStructuralSteelRoute
  '/products/valves': typeof ProductsValvesRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/quality'
    | '/products/fasteners'
    | '/products/flanges'
    | '/products/gaskets'
    | '/products/pipe-fittings'
    | '/products/pipes-tubes'
    | '/products/structural-steel'
    | '/products/valves'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/quality'
    | '/products/fasteners'
    | '/products/flanges'
    | '/products/gaskets'
    | '/products/pipe-fittings'
    | '/products/pipes-tubes'
    | '/products/structural-steel'
    | '/products/valves'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/quality'
    | '/products/fasteners'
    | '/products/flanges'
    | '/products/gaskets'
    | '/products/pipe-fittings'
    | '/products/pipes-tubes'
    | '/products/structural-steel'
    | '/products/valves'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  QualityRoute: typeof QualityRoute
  ProductsFastenersRoute: typeof ProductsFastenersRoute
  ProductsFlangesRoute: typeof ProductsFlangesRoute
  ProductsGasketsRoute: typeof ProductsGasketsRoute
  ProductsPipeFittingsRoute: typeof ProductsPipeFittingsRoute
  ProductsPipesTubesRoute: typeof ProductsPipesTubesRoute
  ProductsStructuralSteelRoute: typeof ProductsStructuralSteelRoute
  ProductsValvesRoute: typeof ProductsValvesRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fasteners': {
      id: '/products/fasteners'
      path: '/products/fasteners'
      fullPath: '/products/fasteners'
      preLoaderRoute: typeof ProductsFastenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/flanges': {
      id: '/products/flanges'
      path: '/products/flanges'
      fullPath: '/products/flanges'
      preLoaderRoute: typeof ProductsFlangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/gaskets': {
      id: '/products/gaskets'
      path: '/products/gaskets'
      fullPath: '/products/gaskets'
      preLoaderRoute: typeof ProductsGasketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pipe-fittings': {
      id: '/products/pipe-fittings'
      path: '/products/pipe-fittings'
      fullPath: '/products/pipe-fittings'
      preLoaderRoute: typeof ProductsPipeFittingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pipes-tubes': {
      id: '/products/pipes-tubes'
      path: '/products/pipes-tubes'
      fullPath: '/products/pipes-tubes'
      preLoaderRoute: typeof ProductsPipesTubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/structural-steel': {
      id: '/products/structural-steel'
      path: '/products/structural-steel'
      fullPath: '/products/structural-steel'
      preLoaderRoute: typeof ProductsStructuralSteelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/valves': {
      id: '/products/valves'
      path: '/products/valves'
      fullPath: '/products/valves'
      preLoaderRoute: typeof ProductsValvesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  QualityRoute: QualityRoute,
  ProductsFastenersRoute: ProductsFastenersRoute,
  ProductsFlangesRoute: ProductsFlangesRoute,
  ProductsGasketsRoute: ProductsGasketsRoute,
  ProductsPipeFittingsRoute: ProductsPipeFittingsRoute,
  ProductsPipesTubesRoute: ProductsPipesTubesRoute,
  ProductsStructuralSteelRoute: ProductsStructuralSteelRoute,
  ProductsValvesRoute: ProductsValvesRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
